### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by slashmili** [WhoopInc/dogstatsde#16]
Hi,

The Versioning looks a bit off
- In hex the version is  `0.6.0` (https://hex.pm/packages/dogstatsde)
- In README version `1.0.0` is mentioned  (https://github.com/WhoopInc/dogstatsde/blob/master/README.md#elixir)
- In mix.exs the version is `0.5.1` https://github.com/WhoopInc/dogstatsde/blob/master/mix.exs#L22

Could you update the versions?
For now I'm using master but would be great if you resolve it

BTW thanks for datadog tool, it's great 🎉

**Comment by waisbrot** [comment]
Thanks for the notes! 

Do you use Mix? I'd like to put some constant in the version spot for mix.exs (like how I declare the Erlang app version as [`git`](https://github.com/WhoopInc/dogstatsde/blob/master/src/dogstatsd.app.src#L3) ) and have it get resolved to a proper semver at release-time. I wasn't able to find documentation, though. If there's no official way to do it, I may hard-code a version of "0.0.1" and then overwrite it with the real version before pushing to Hex.

**Comment by waisbrot** [comment]
I tried pushing a couple versions to Hex but haven't had much success. What it looks like to me is that Mix is seeing a `rebar.config` file and ignoring my `mix.exs` file. I'll try to take a look at this again later, but I'm out of debugging time for it right now.

**Comment by waisbrot** [comment]
I think I've got a handle on things now.

Before, I was trying to give a more Elixir-natural interface by making a Dogstatsd module that wrapped the erlang dogstatsd module. One Mix decided that it understood rebar3, this stopped working (because Mix would do a straight Erlang compile and ignore my wrapper).

So I've dropped the wrapper now (it was more of a fun bit of Elixir for me than something useful, I think) and instead I added a little example Elixir project showing how to use it. https://github.com/WhoopInc/dogstatsde/tree/master/examples/elixir The example gets run as part of the tests, so it should keep me from breaking Elixir support.

This is in Hex as 0.8.0, and I think I fixed all the disagreeing version numbers :-)
